--INSERT INTO users (id, pseudo, email, password, role, token) values(NULL, 'first', 'first@first.com', 'first', 'ADMIN', 'fjnverikferi')
--INSERT INTO users (id, pseudo, email, password, role, token) values(NULL, 'second', 'second@second.com', 'second', 'USER', 'dvekrgerg')
--INSERT INTO users (id, pseudo, email, password, role, token) values(NULL, 'three', 'three@three.com', 'three', 'USER', 'ekrrfhcnekf')
