--INSERT INTO users (id, pseudo, email, password) values(null, 'first', 'first@first.com', 'first')
--INSERT INTO users (id, pseudo, email, password) values(null, 'second', 'second@second.com', 'second')
--INSERT INTO users (id, pseudo, email, password) values(null, 'three', 'three@three.com', 'three')