INSERT INTO users (id, pseudo, email, password, role, token) values(1, 'first', 'first@first.com', 'first', 'ADMIN', 'sfnhierf35V0FDDCZE40RC30A20Z')
INSERT INTO users (id, pseudo, email, password, role, token) values(2, 'second', 'second@second.com', 'second', 'USER', 'fifgnvoirg657HVT4')
INSERT INTO users (id, pseudo, email, password, role, token) values(3, 'three', 'three@three.com', 'three', 'USER', 'rfrjf456456HFvefrce')
INSERT INTO users (id, pseudo, email, password, role, token) values(4, 'Yousria', 'yous@yous.fr', '$2a$10$KJ9ZWCmY3lf7ipPoq5jmYOqYcd4Vk1v3T9bZ/F9ELc.ECotfZPzV6', 'USER', 'eyJhbGciOiJIUzI1NiJ9.eyJwYXNzd29yZCI6InlvdXNyaWExMjM0IiwiYWRtaW4iOmZhbHNlLCJ1c2VybmFtZSI6IllvdXNyaWEifQ.4tiqXkprT1K7kkZES15c7yU-jW8-y8lyXb6wqYt-igs')
INSERT INTO album(id,title,users) values(1,'albumtest',1)
INSERT INTO album(id,title,users) values(2,'albumtest2',1)
INSERT INTO image(id,title,likescore,dislikescore,datas,album_photo)values(1,'testimage',5,6,null,1)
INSERT INTO image(id,title,likescore,dislikescore,datas,album_photo)values(2,'testimage2',3,5,null,2)
INSERT INTO image(id,title,likescore,dislikescore,datas,album_photo)values(3,'testimage3',1,6,null,1)
INSERT INTO image(id,title,likescore,dislikescore,datas,album_photo)values(4,'testimage4',3,5,null,2)
INSERT INTO image(id,title,likescore,dislikescore,datas,album_photo)values(5,'testimage5',1,6,null,1)
INSERT INTO image(id,title,likescore,dislikescore,datas,album_photo)values(6,'testimage6',3,5,null,2)
INSERT INTO image(id,title,likescore,dislikescore,datas,album_photo)values(7,'testimage7',1,6,null,1)
INSERT INTO comments(id,user_id,comment,image_id) values(null,4,'BONJOURBONJOUR',1)